# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import atuador_pb2 as atuador__pb2


class AtuadorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LigarLampada = channel.unary_unary(
                '/atuador.Atuador/LigarLampada',
                request_serializer=atuador__pb2.Solicitacao.SerializeToString,
                response_deserializer=atuador__pb2.Resposta.FromString,
                )
        self.DesligarLampada = channel.unary_unary(
                '/atuador.Atuador/DesligarLampada',
                request_serializer=atuador__pb2.Solicitacao.SerializeToString,
                response_deserializer=atuador__pb2.Resposta.FromString,
                )
        self.LigarAquecedor = channel.unary_unary(
                '/atuador.Atuador/LigarAquecedor',
                request_serializer=atuador__pb2.Solicitacao.SerializeToString,
                response_deserializer=atuador__pb2.Resposta.FromString,
                )
        self.DesligarAquecedor = channel.unary_unary(
                '/atuador.Atuador/DesligarAquecedor',
                request_serializer=atuador__pb2.Solicitacao.SerializeToString,
                response_deserializer=atuador__pb2.Resposta.FromString,
                )
        self.LigarControleIncendio = channel.unary_unary(
                '/atuador.Atuador/LigarControleIncendio',
                request_serializer=atuador__pb2.Solicitacao.SerializeToString,
                response_deserializer=atuador__pb2.Resposta.FromString,
                )
        self.DesligarControleIncendio = channel.unary_unary(
                '/atuador.Atuador/DesligarControleIncendio',
                request_serializer=atuador__pb2.Solicitacao.SerializeToString,
                response_deserializer=atuador__pb2.Resposta.FromString,
                )


class AtuadorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LigarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesligarLampada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LigarAquecedor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesligarAquecedor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LigarControleIncendio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesligarControleIncendio(self, request, context):
        """Adicione mais métodos conforme necessário
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtuadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LigarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.LigarLampada,
                    request_deserializer=atuador__pb2.Solicitacao.FromString,
                    response_serializer=atuador__pb2.Resposta.SerializeToString,
            ),
            'DesligarLampada': grpc.unary_unary_rpc_method_handler(
                    servicer.DesligarLampada,
                    request_deserializer=atuador__pb2.Solicitacao.FromString,
                    response_serializer=atuador__pb2.Resposta.SerializeToString,
            ),
            'LigarAquecedor': grpc.unary_unary_rpc_method_handler(
                    servicer.LigarAquecedor,
                    request_deserializer=atuador__pb2.Solicitacao.FromString,
                    response_serializer=atuador__pb2.Resposta.SerializeToString,
            ),
            'DesligarAquecedor': grpc.unary_unary_rpc_method_handler(
                    servicer.DesligarAquecedor,
                    request_deserializer=atuador__pb2.Solicitacao.FromString,
                    response_serializer=atuador__pb2.Resposta.SerializeToString,
            ),
            'LigarControleIncendio': grpc.unary_unary_rpc_method_handler(
                    servicer.LigarControleIncendio,
                    request_deserializer=atuador__pb2.Solicitacao.FromString,
                    response_serializer=atuador__pb2.Resposta.SerializeToString,
            ),
            'DesligarControleIncendio': grpc.unary_unary_rpc_method_handler(
                    servicer.DesligarControleIncendio,
                    request_deserializer=atuador__pb2.Solicitacao.FromString,
                    response_serializer=atuador__pb2.Resposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atuador.Atuador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Atuador(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LigarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/atuador.Atuador/LigarLampada',
            atuador__pb2.Solicitacao.SerializeToString,
            atuador__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DesligarLampada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/atuador.Atuador/DesligarLampada',
            atuador__pb2.Solicitacao.SerializeToString,
            atuador__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LigarAquecedor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/atuador.Atuador/LigarAquecedor',
            atuador__pb2.Solicitacao.SerializeToString,
            atuador__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DesligarAquecedor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/atuador.Atuador/DesligarAquecedor',
            atuador__pb2.Solicitacao.SerializeToString,
            atuador__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LigarControleIncendio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/atuador.Atuador/LigarControleIncendio',
            atuador__pb2.Solicitacao.SerializeToString,
            atuador__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DesligarControleIncendio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/atuador.Atuador/DesligarControleIncendio',
            atuador__pb2.Solicitacao.SerializeToString,
            atuador__pb2.Resposta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
